# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content
  title: BioCosmo
  params:
    description: BioCosmo

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: BioCosmo
#  params:
#    description: BioCosmo
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
