# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 11
  - name: News
    url: post
    weight: 12
  - name: People
    url: people
    weight: 13
  - name: Events
    url: event
    weight: 14
  - name: Where-I-Go
    parent: event
    url: event/whereIGo/
    weight: 15
  - name: Research Seminar
    parent: event
    url: event/ResearchSeminar/
    weight: 16
  - name: Life Sciences Pioneer
    parent: event
    url: event/LifeSciencesPioneer/
    weight: 17
  - name: Contact
    url: contact
    weight: 18
